# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 389b818f3fdbfcd16548cce749a099b233e21096ab86a3ede547e037d04012ea3a4d0e1bbce906311a71308f2a7f0ac626a7f9a7cbc252edbc6747a67d6c3349

test:
  secret_key_base: 8f911b261e5179e3f0b21caefe9285901f5744078cbb5a8c4aa12050f780aff3449c38fabe5a76e9d22c5a2460e5e0ef65a425fba65e1c50be1e07f588a74751

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
